export const authorList = [
  {
    id: 1,
    authorName: 'Yash Govani',
    imgUrl: 'customer-1.jpg',
    description: 'Yash is a chef who living in Ahmedabad',
    followers: 22,
  },
  {
    id: 2,
    authorName: 'Dhruvi Rami',
    imgUrl: 'customer-2.jpg',
    description: 'Dhruvi is a chef who living in Mumbai',
    followers: 70,
  },
  {
    id: 3,
    authorName: 'Meet Ahya',
    imgUrl: 'customer-3.jpg',
    description: 'Meet is a chef who living in Porbandar',
    followers: 55,
  },
];

export const recipeList = [
  {
    id: 1,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '8.jpg',
    time: 20,
    author: [
      {
        id: 1,
        authorName: 'Yash Govani',
        imgUrl: 'customer-1.jpg',
        description: 'Yash is a chef who living in Ahmedabad',
        followers: 22,
      },
    ],
  },
  {
    id: 2,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '1.jpg',
    time: 20,
    author: [
      {
        id: 2,
        authorName: 'Dhruvi Rami',
        imgUrl: 'customer-2.jpg',
        description: 'Dhruvi is a chef who living in Mumbai',
        followers: 70,
      },
    ],
  },
  {
    id: 3,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '2.jpg',
    time: 20,
    author: [
      {
        id: 3,
        authorName: 'Meet Ahya',
        imgUrl: 'customer-3.jpg',
        description: 'Meet is a chef who living in Porbandar',
        followers: 55,
      },
    ],
  },
  {
    id: 4,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '3.jpg',
    time: 20,
    author: [
      {
        id: 1,
        authorName: 'Yash Govani',
        imgUrl: 'customer-1.jpg',
        description: 'Yash is a chef who living in Ahmedabad',
        followers: 22,
      },
    ],
  },
  {
    id: 5,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '4.jpg',
    time: 20,
    author: [
      {
        id: 2,
        authorName: 'Dhruvi Rami',
        imgUrl: 'customer-2.jpg',
        description: 'Dhruvi is a chef who living in Mumbai',
        followers: 70,
      },
    ],
  },
  {
    id: 6,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '5.jpg',
    time: 20,
    author: [
      {
        id: 3,
        authorName: 'Meet Ahya',
        imgUrl: 'customer-3.jpg',
        description: 'Meet is a chef who living in Porbandar',
        followers: 55,
      },
    ],
  },
  {
    id: 7,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '6.jpg',
    time: 20,
    author: [
      {
        id: 1,
        authorName: 'Yash Govani',
        imgUrl: 'customer-1.jpg',
        description: 'Yash is a chef who living in Ahmedabad',
        followers: 22,
      },
    ],
  },
  {
    id: 8,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '7.jpg',
    time: 20,
    author: [
      {
        id: 2,
        authorName: 'Dhruvi Rami',
        imgUrl: 'customer-2.jpg',
        description: 'Dhruvi is a chef who living in Mumbai',
        followers: 70,
      },
    ],
  },
  {
    id: 9,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '8.jpg',
    time: 20,
    author: [
      {
        id: 3,
        authorName: 'Meet Ahya',
        imgUrl: 'customer-3.jpg',
        description: 'Meet is a chef who living in Porbandar',
        followers: 55,
      },
    ],
  },
  {
    id: 10,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '1.jpg',
    time: 20,
    author: [
      {
        id: 1,
        authorName: 'Yash Govani',
        imgUrl: 'customer-1.jpg',
        description: 'Yash is a chef who living in Ahmedabad',
        followers: 22,
      },
    ],
  },
  {
    id: 11,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '5.jpg',
    time: 20,
    author: [
      {
        id: 2,
        authorName: 'Dhruvi Rami',
        imgUrl: 'customer-2.jpg',
        description: 'Dhruvi is a chef who living in Mumbai',
        followers: 70,
      },
    ],
  },
  {
    id: 12,
    recipeName: 'Noodles',
    serve: 4,
    ingredients: [
      { name: 'onion', quantity: 1, parameter: '' },
      { name: 'capsicum', quantity: 1, parameter: '' },
      { name: 'Garlic', quantity: 1, parameter: '' },
      { name: 'Noodles', quantity: 250, parameter: 'Gram' },
      { name: 'corn floor', quantity: 100, parameter: 'Gram' },
      { name: 'soya sause', quantity: 4, parameter: 'table spoon' },
      { name: 'red/green chilly sause', quantity: 3, parameter: 'table spoon' },
      { name: 'vinegar', quantity: 1, parameter: 'table spoon' },
      { name: 'olive oil', quantity: 2, parameter: 'table spoon' },
    ],
    description:
      'i am a huge fan of indo chinese recipes and i make it often for my evening snacks. particularly the combination of manchurian with a stir fry noodles or rice is my personal favourite. however my husband is a huge fan of simple noodles without much fancy sauce and spices in it. hence i have to make it frequently for his daily lunch box. he likes it to be soupy with more water in it, similar to noodle soup. i like it to be spicy with a topping of schezwan sauce on it. so once the noodles are made, i make 2 portions and proceed further with my required toppings and sauce as per my preference. i would also recommend you guys to try with any choice of manchurian dish with noodles or fried rice.',
    imagePath: '3.jpg',
    time: 20,
    author: [
      {
        id: 3,
        authorName: 'Meet Ahya',
        imgUrl: 'customer-3.jpg',
        description: 'Meet is a chef who living in Porbandar',
        followers: 55,
      },
    ],
  },
];
